
package view;

import controller.ForecastController;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Database_Connection;
import model.Database_Search;

/**
 *
 * @author 
 */
public class Weighted_moving_a_frame extends javax.swing.JFrame {

    String[] months = new String[3];
    double[] months_sales = new double[3];

    /**
     * Creates new form Weighted_moving_a_frame
     */
    public Weighted_moving_a_frame() {
        initComponents();
        loadingProductID();
    }

    private void loadingProductID() {
        this.sales.setText("");
        try {
            ResultSet result = new Database_Search().load_ProductIDs();
            while (result.next()) {
                String nextOrderID = result.getString(1);
                this.producIdCombo.addItem(nextOrderID);
            }
            Database_Connection.close_Connection();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        producIdCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        current_month_lable = new javax.swing.JLabel();
        sales = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        weight_1_field = new javax.swing.JTextField();
        weight_2_field = new javax.swing.JTextField();
        weight_3_field = new javax.swing.JTextField();
        month_1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cancelBTN = new javax.swing.JButton();
        cancelBTN1 = new javax.swing.JButton();
        month_2 = new javax.swing.JLabel();
        month_3 = new javax.swing.JLabel();
        sale_1_lable = new javax.swing.JLabel();
        sale_2_lable = new javax.swing.JLabel();
        sale_3_lable = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText("Weighted Moving Average");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Product ID    :");

        producIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producIdComboActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Forecast for ");

        current_month_lable.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        current_month_lable.setForeground(new java.awt.Color(0, 204, 204));

        sales.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        sales.setForeground(new java.awt.Color(0, 204, 204));
        sales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sales.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText(" : ");

        weight_1_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight_1_fieldActionPerformed(evt);
            }
        });

        month_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        month_1.setText(".");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Weight");

        cancelBTN.setText("Cancel");
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });

        cancelBTN1.setText("Calculate");
        cancelBTN1.setToolTipText("");
        cancelBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTN1ActionPerformed(evt);
            }
        });

        month_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        month_2.setText(".");

        month_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        month_3.setText(".");

        sale_1_lable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sale_1_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sale_1_lable.setText("0");

        sale_2_lable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sale_2_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sale_2_lable.setText("0");

        sale_3_lable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sale_3_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sale_3_lable.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Month");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sales Qty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(month_3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sale_3_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(month_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sale_2_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(month_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sale_1_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weight_3_field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(weight_2_field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cancelBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(weight_1_field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(producIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(current_month_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sales, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month_1)
                    .addComponent(sale_1_lable)
                    .addComponent(weight_1_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month_2)
                    .addComponent(sale_2_lable)
                    .addComponent(weight_2_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month_3)
                    .addComponent(sale_3_lable)
                    .addComponent(weight_3_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(cancelBTN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(current_month_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(sales)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelBTN)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void producIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producIdComboActionPerformed

        getCurrentDate();
    }//GEN-LAST:event_producIdComboActionPerformed

    private void getCurrentDate() {

        ForecastController forecastController = new ForecastController();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date(); //todays date
        Calendar c_start = Calendar.getInstance();    //calender start date    

        date.setDate(1); // set to 1st day of the month
        c_start.setTime(date);
        //c_start.add(Calendar.MONTH, 1);
        this.current_month_lable.setText(new SimpleDateFormat("yyyy-MMMM").format(c_start.getTime()));
        //c_start.add(Calendar.MONTH, -1); // get to the current month 
        c_start.add(Calendar.MONTH, -1);
        for (int i = 1; i < 4; i++) {
            c_start.add(Calendar.MONTH, -1);
            String month_start = dateFormat.format(c_start.getTime());

            c_start.add(Calendar.MONTH, 1);
            String month_end = dateFormat.format(c_start.getTime());

            // calling database
            months_sales[i - 1] = forecastController.get_soled_items_for_month(this.producIdCombo.getSelectedItem(), month_start, month_end);

            String currentDate2 = new SimpleDateFormat("yyyy-MMMM").format(c_start.getTime());
            c_start.add(Calendar.MONTH, -1);
            months[i - 1] = currentDate2;
        }
        this.month_1.setText(months[0]);
        this.month_2.setText(months[1]);
        this.month_3.setText(months[2]);
        this.sale_1_lable.setText(String.valueOf(months_sales[0]));
        this.sale_2_lable.setText(String.valueOf(months_sales[1]));
        this.sale_3_lable.setText(String.valueOf(months_sales[2]));

    }


    private void weight_1_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight_1_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight_1_fieldActionPerformed

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        this.dispose();
        Marketing_Screen marketing_Screen = new Marketing_Screen();
        marketing_Screen.setVisible(true);
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void cancelBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTN1ActionPerformed

        this.sales.setText("");

        if (this.weight_1_field.getText().equals("") || this.weight_2_field.getText().equals("") || this.weight_3_field.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Fill weight fields", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            double forecast = 0;
            double w1 = 0, w2 = 0, w3 = 0;
            boolean calculate = false;
            try {
                w1 = Double.valueOf(this.weight_1_field.getText());
                w2 = Double.valueOf(this.weight_2_field.getText());
                w3 = Double.valueOf(this.weight_3_field.getText());
                calculate = true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Enter numaric values", "Error", JOptionPane.ERROR_MESSAGE);
                calculate = false;
            }
            if (calculate) {
                for (int i = 0; i < months_sales.length; i++) {
                    System.out.println("sales" + months_sales[i]);
                }

                if (w1 + w2 + w3 == 100) {

                    forecast = (w1 * months_sales[0] / 100) + (w2 * months_sales[1] / 100) + (w3 * months_sales[2] / 100);
                    this.sales.setText(String.format("%.02f", ((float) forecast)));
                } else {
                    JOptionPane.showMessageDialog(null, "Total of weight should be 100", "Error", JOptionPane.ERROR_MESSAGE);

                }

            }

        }

    }//GEN-LAST:event_cancelBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Weighted_moving_a_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Weighted_moving_a_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Weighted_moving_a_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Weighted_moving_a_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Weighted_moving_a_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBTN;
    private javax.swing.JButton cancelBTN1;
    private javax.swing.JLabel current_month_lable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel month_1;
    private javax.swing.JLabel month_2;
    private javax.swing.JLabel month_3;
    private javax.swing.JComboBox<String> producIdCombo;
    private javax.swing.JLabel sale_1_lable;
    private javax.swing.JLabel sale_2_lable;
    private javax.swing.JLabel sale_3_lable;
    private javax.swing.JLabel sales;
    private javax.swing.JTextField weight_1_field;
    private javax.swing.JTextField weight_2_field;
    private javax.swing.JTextField weight_3_field;
    // End of variables declaration//GEN-END:variables
}
